import { ApplicationConfig, provideZoneChangeDetection, importProvidersFrom, LOCALE_ID } from '@angular/core';
import { provideRouter } from '@angular/router';
import { provideHttpClient, withInterceptors } from '@angular/common/http';
import { registerLocaleData } from '@angular/common';
import localeEs from '@angular/common/locales/es';

registerLocaleData(localeEs);

import { 
  LucideAngularModule, 
  LayoutDashboard, 
  Users, 
  CircleDollarSign, 
  History, 
  ShieldCheck, 
  LogOut, 
  Menu,
  X,
  ChevronRight,
  TrendingUp,
  Clock,
  ArrowUpRight,
  ArrowDownRight,
  Plus,
  Save,
  Settings,
  CheckCircle2,
  XCircle,
  Mail,
  Lock,
  Eye,
  EyeOff,
  ArrowRight,
  Loader2,
  Search,
  Phone,
  MoreHorizontal,
  Trash2,
  MapPin,
  IdCard,
  Wallet,
  Calendar,
  AlertTriangle,
  Home,
  Key,
  Shield,
  User,
  Bell,
  AlertCircle,
  Check,
  Info,
  UserPlus,
  ChevronDown,
  Calculator,
  Circle,
  RefreshCw,
  Edit2,
  Building,
  ArrowLeft,
  Layers,
  Percent,
  Banknote,
  Filter,
  Bookmark
} from 'lucide-angular';

import { routes } from './app.routes';
import { authInterceptor } from './core/interceptors/auth.interceptor';

export const appConfig: ApplicationConfig = {
  providers: [
    { provide: LOCALE_ID, useValue: 'es' },
    provideZoneChangeDetection({ eventCoalescing: true }),
    provideRouter(routes),
    provideHttpClient(withInterceptors([authInterceptor])),
    importProvidersFrom(
      LucideAngularModule.pick({ 
        LayoutDashboard, 
        Users, 
        CircleDollarSign, 
        History, 
        ShieldCheck, 
        LogOut, 
        Menu,
        X,
        ChevronRight,
        TrendingUp,
        Clock,
        Calculator,
        ArrowUpRight,
        ArrowDownRight,
        Plus,
        Save,
        Settings,
        CheckCircle2,
        XCircle,
        Mail,
        Lock,
        Eye,
        EyeOff,
        ArrowRight,
        Loader2,
        Search,
        Phone,
        MoreHorizontal,
        Trash2,
        MapPin,
        IdCard,
        Wallet,
        Calendar,
        AlertTriangle,
        Home,
        Key,
        Shield,
        User,
        Bell,
        AlertCircle,
        Check,
        Info,
        UserPlus,
        ChevronDown,
        Circle,
        RefreshCw,
        Edit2,
        Building,
        ArrowLeft,
        Layers,
        Percent,
        Banknote,
        Filter,
        Bookmark
      })
    )
  ],
};
